2023-Jun-14 15:39:13 logging_module_handler  INFO: test info level with handler
2023-Jun-14 15:39:13 logging_module_handler  WARNING: test warning level with handler
2023-Jun-14 15:45:57 logging_module_handler  INFO: test info level with handler
2023-Jun-14 15:45:57 logging_module_handler  WARNING: test warning level with handler
2023-Jun-14 15:46:14 logging_module_handler  INFO: test info level with handler
2023-Jun-14 15:46:14 logging_module_handler  WARNING: test warning level with handler
2023-Jun-14 15:46:14 logging_module_handler  ERROR: exception occurred
Traceback (most recent call last):
  File "c:\MyWorkSpace\MEDTRONICS\PIS System Sample Codes\Logging\logging_module.py", line 59, in <module>
    print(vals[4])
          ~~~~^^^
IndexError: list index out of range
